version: "3.8"

services:
  twatter-server:
    image: golang:1.17.3-alpine
    command: >
      sh -c "go get github.com/canthefason/go-watcher &&
      go install github.com/canthefason/go-watcher/cmd/watcher &&
      go install &&
      watcher"
    ports:
      - 3001:3001
    working_dir: /twatter-server
    volumes:
      - ./:/twatter-server
    environment:
      ENV: dev
      PORT: 3001
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/twatter_dev

      SESSION_KEY: randomlygeneratedstringhere

      ALLOWED_ORIGINS: http://localhost:3000

      API_DOMAIN_URL: http://localhost:3001
      FRONTEND_DOMAIN_URL: http://localhost:3000
      DOMAIN: localhost
      CDN_DOMAIN_URL: http://localhost:5000

      SUPPORT_EMAIL: email@example.com
      SUPPORT_EMAIL_PASSWORD: examplepassword
      SMTP_HOST: mail.example.com
      SMTP_PORT: 587

      REDIS_HOST: redis:6379
      REDIS_PASSWORD: 
      REDIS_DB_NUM: 0

    depends_on:
      - redis
      - postgres

    networks:
      - twatter

  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - twatter

  postgres:
    image: postgres:12.8-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twatter_dev
    networks:
      - twatter

volumes:
  redis-data:
  postgres-data:

networks:
  twatter:
    name: twatter
